name: detection_and_visualization
# root: ~/

startup_window: main
# startup_pane: 1
pre_window: rosparam set use_sim_time 1

windows:
  - main:
      layout: tiled
      panes:
        - roslaunch uav_detect detect_depth.launch
        - roslaunch uav_detect localize_single.launch
        - roslaunch uav_detect display_detections.launch
        - roslaunch uav_detect backproject_location.launch
  - rqt_reconfigure:
      layout: even-vertical
      panes:
        - rosrun rqt_reconfigure rqt_reconfigure
  - static_transform_publisher:
      layout: even-vertical
      panes:
        - rosrun tf2_ros static_transform_publisher 0 0 0 1.57 3.14 1.57 _color_optical_frame local_origin
  - bash:
      layout: even-vertical
      panes:
        - mv -n layout-UAV_LOCALIZATION.json ~/.layouts/; ~/.i3/layout_manager.sh UAV_LOCALIZATION
