# points of the input pointcloud, closer than this size, are discarded
filtering_leaf_size: 0.5 # meters

max_speed_error: 3.8 # metres per second

cov_coeffs:
  xy:
    mav:              0.1
    ball:             0.05
    mav_with_ball:    0.01
  z:
    mav:              0.1
    ball:             0.05
    mav_with_ball:    0.03
  xyz:
    velocity: 0.4 # radians

linefit:
  neighborhood: 5 # metres
  point_max_age: 3.0 # seconds per neighborhood size

classification:
  max_detection_height: 2.5 # metres
  max_mav_height: 1.0 # metres
  max_detection_width: 2.0 # metres
  ball_wire_length: 1.45 # metres
  close_distance: 9 # metres
  mav_width: 0.450 # metres
  ball_width: 0.11 # metres

plane_fit:
  min_points: 80
  ransac_threshold: 1.0 # metres

safety_area:
  offset: [3.0, 3.0]
  deflation: 4.5 # metres
  height:
    min: 3.5 # metres
    max: 18 # metres
  left_cut_plane:
    normal: [-5.0, 2.0]
    offset:  999.0
  right_cut_plane:
    normal: [-5.0, 2.0]
    offset: -999.0

# points inside the box, defined by *uav_exclude_box*, relative to the sensor, are discarded
# this is used to filter out the MAV itself from the pointcloud
exclude_box:
  offset: # offset of the box center relative to the sensor origin
    x: 0.35 # meters
    y: 0 # meters
    z: -0.5 # meters
  size:
    x: 1.7 # meters
    y: 1.7 # meters
    z: 1 # meters

keep_pc_organized: true
