# if an estimated speed of a detection candidate is higher than this, it is discarded
max_speed_error: 3.8 # meters per second

# these coefficients are used to construct the covariance matrix of the detections
# according to its class
cov_coeffs:
  xy:
    mav:              0.1
    ball:             0.05
    mav_with_ball:    0.01
  z:
    mav:              0.1
    ball:             0.05
    mav_with_ball:    0.03
  xyz:
    velocity: 0.4 # meters per second

# parameters of the linefitting algorithm for velocity estimation
linefit:
  neighborhood: 5 # metres
  point_max_age: 3.0 # seconds per neighborhood size

# parameters of the cluster classification algorithm
classification:
  max_detection_height: 2.5 # metres
  max_mav_height: 1.0 # metres
  max_detection_width: 2.0 # metres
  ball_wire_length: 1.45 # metres
  close_distance: 9 # metres
  mav_width: 0.450 # metres
  ball_width: 0.11 # metres

# the safety area is loaded from a ROS message and then deflated by the specified amount
# and optionally cut by a left/right plane to obtain the operational area
safety_area:
  offset: [3.0, 3.0]
  deflation: 4.5 # metres
  height:
    min: 3.5 # metres
    max: 18 # metres
  left_cut_plane:
    normal: [-5.0, 2.0]
    offset:  999.0
  right_cut_plane:
    normal: [-5.0, 2.0]
    offset: -999.0

# points inside the box, defined by *uav_exclude_box*, relative to the sensor, are discarded
# this is used to filter out the MAV itself from the pointcloud
exclude_box:
  offset: # offset of the box center relative to the sensor origin
    x: 0.35 # meters
    y: 0 # meters
    z: -0.5 # meters
  size:
    x: 1.7 # meters
    y: 1.7 # meters
    z: 1 # meters
