!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  blur_empty_areas: false
  dilate_iterations: 3
  erode_ignore_empty_iterations: 5
  erode_iterations: 5
  filter_by_area: true
  filter_by_circularity: true
  filter_by_color: true
  filter_by_convexity: true
  filter_by_inertia: true
  filter_by_known_pixels: true
  filter_by_orientation: true
  gaussianblur_size: 0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Depth_blob_detection_parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                dictitems:
                  Blob_filtering: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      filter_by_area: true
                      filter_by_circularity: true
                      filter_by_color: true
                      filter_by_convexity: true
                      filter_by_inertia: true
                      filter_by_known_pixels: true
                      filter_by_orientation: true
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 3
                      max_angle: 0.4
                      max_area: 10000
                      max_circularity: 0.9
                      max_convexity: 1.0
                      max_depth: 60000
                      max_inertia_ratio: 0.9
                      min_angle: 0.0
                      min_area: 200
                      min_circularity: 0.3
                      min_convexity: 0.75
                      min_depth: 1000
                      min_dist_between: 10.0
                      min_inertia_ratio: 0.01
                      min_known_pixels: 100
                      min_repeatability: 8
                      name: Blob_filtering
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 1
                      state: true
                      type: ''
                    state: []
                  Deprecated: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      blur_empty_areas: false
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 4
                      name: Deprecated
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 1
                      state: true
                      threshold_step: 1000
                      threshold_width: 100
                      type: ''
                      use_threshold_width: false
                    state: []
                  Image_preprocessing: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      dilate_iterations: 3
                      erode_ignore_empty_iterations: 5
                      erode_iterations: 5
                      gaussianblur_size: 0
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 2
                      medianblur_size: 0
                      name: Image_preprocessing
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 1
                      state: true
                      structuring_element_size: 3
                      type: ''
                    state: []
                state: []
              id: 1
              name: Depth_blob_detection_parameters
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  max_angle: 0.4
  max_area: 10000
  max_circularity: 0.9
  max_convexity: 1.0
  max_depth: 60000
  max_inertia_ratio: 0.9
  medianblur_size: 0
  min_angle: 0.0
  min_area: 200
  min_circularity: 0.3
  min_convexity: 0.75
  min_depth: 1000
  min_dist_between: 10.0
  min_inertia_ratio: 0.01
  min_known_pixels: 100
  min_repeatability: 8
  structuring_element_size: 3
  threshold_step: 1000
  threshold_width: 100
  use_threshold_width: false
state: []
