# image preprocessing
blur_empty_areas: false

dilate_iterations: 0
erode_iterations: 0
erode_ignore_empty_iterations: 5

gaussianblur_size: 0
medianblur_size: 0

# filtration of detected blobs
blob_filter_by_area: true
blob_min_area: 20
blob_max_area: 5000

blob_filter_by_circularity: true
blob_min_circularity: 0.3
blob_max_circularity: 0.8

blob_filter_by_orientation: true
blob_min_angle: 0.0
blob_max_angle: 0.4

blob_filter_by_inertia: true
blob_min_inertia_ratio: 0.01
blob_max_inertia_ratio: 0.4

blob_filter_by_convexity: true
blob_min_convexity: 0.75
blob_max_convexity: 1.0

blob_filter_by_color: true
min_depth: 4000
max_depth: 13000

# further filtration
blob_min_dist_between: 10.0
blob_min_repeatability: 4

# deprecated parameters
use_threshold_width: false
blob_threshold_step: 500
blob_threshold_width: 100
