lkf_dt: 0.02

# frame names
# uav_frame: 'fcu_uav'
# use_ocam: true

# ############### Camera parameters (for top-mounted Mobius cam) ###############
# camera_delay: 130 # ms

# camera_offset_x: 0.0
# camera_offset_y: 0.24
# camera_offset_z: -0.11

# camera_offset_roll: 90.0
# camera_offset_pitch: -120.0
# camera_offset_yaw: 0.0

# # Simulation parameters
# # camera_offset_x: 0.0
# # camera_offset_y: -0.04
# # camera_offset_z: -0.2

# # camera_offset_roll: 45 #degrees
# # camera_offset_pitch: -90  #degrees
# # camera_offset_yaw: 45  #degrees

# ############### Depthmap related parameters  ###############
# height_threshold: 1.0 # metres above ground
# bg_dist: 1.0 # metres from background to be filtered

# ############### Distance estimation parameters ###############
# UAV_width: 0.3 # metres
# dist_filter_window: 3
# max_dist: 15.0
xy_covariance_coeff: 0.1
z_covariance_coeff: 0.3
max_update_divergence: 5.0
max_lkf_uncertainty: 50.0
lkf_process_noise: 0.3
init_vel_cov: 4.0
# dist_corr_p0: -1.0
# dist_corr_p1: 0.7

# ############### Position estimation parameters ###############
# min_x: -.inf
# max_x: .inf
# min_y: -.inf
# max_y: .inf
# min_z: 0.0
# max_z: .inf
