# Localization parameters

# LKF update rate
lkf_dt: 0.02 # seconds
# Default covariance of the detection measurement in the XY direction (in camera CS)
xy_covariance_coeff: 0.1
# Covariance coefficient of the detection measurement in the Z direction (in camera CS)
# This coefficient is scaled by z*sqrt(z) to obtain the resulting covariance in Z direction.
z_covariance_coeff: 0.3
# Maximal divergence between a measurement and a LKF for the measurement to be considered
# for association to the LKF
max_update_divergence: 5.0
# If a LKF exceeds this uncertainty, it is kicked out of the pool of active LKFs.
max_lkf_uncertainty: 1.0
# Process noise of the LKF position states
lkf_process_noise_pos: 1.0  # it is scaled by dt in the code, so should it be given scaled to seconds here
# Process noise of the LKF velocity states
lkf_process_noise_vel: 3.0  # it is scaled by dt in the code, so should it be given scaled to seconds here
# Initial covariance of velocity states at LKF initialization
init_vel_cov: 4.0
# A LKF must have received at least this many corrections before it is considered as
# a candidate for publishing.
min_corrs_to_consider: 20
