name: simulation
root: ~/

startup_window: takeoff
# startup_pane: 1

windows:
  - gazebo:
      layout: even-vertical
      panes:
        - export DISPLAY=:1; roslaunch uav_detect simulation.launch
        # - roslaunch simulation simulation.launch
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; spawn 1 --run --delete --enable-rangefinder --enable-ground-truth --enable-realsense-front --enable-realistic-realsense
        - waitForSimulation; spawn 2 --run --delete --enable-rangefinder --enable-ground-truth
  - odometry:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch mrs_mav_manager simulation.launch
        - export UAV_NAME=uav2; waitForOdometry; roslaunch mrs_mav_manager simulation.launch
  - takeoff:
      layout: even-vertical
      panes:
        #{ takeoff uav1
        - '
          export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
          rosservice call /$UAV_NAME/control_manager/motors 1;
          rosservice call /$UAV_NAME/mav_manager/takeoff;
          sleep 5;
          rosservice call /$UAV_NAME/control_manager/switch_tracker mrs_trackers/LineTracker;
          rosservice call /$UAV_NAME/control_manager/goto "goal: [-5.0, 0.0, 5.0, 0.0]"
          '
        #}
        #{ takeoff uav2
        - '
          export UAV_NAME=uav2;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
          rosservice call /$UAV_NAME/control_manager/motors 1;
          rosservice call /$UAV_NAME/mav_manager/takeoff;
          sleep 5;
          rosservice call /$UAV_NAME/control_manager/switch_tracker mrs_trackers/LineTracker;
          rosservice call /$UAV_NAME/control_manager/goto "goal: [4.0, 0.0, 5.0, 0.0]"
          '
        #}
  - random_flier:
      layout: even-vertical
      panes:
        - '
          export UAV_NAME=uav2; waitForControl;
          sleep 10;
          roslaunch uav_detect random_flier.launch
          '
